config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "questions#index"

  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base

belongs_to :question
belongs_to :user

validates_presence_of :user_id
validates_presence_of :question_id

validates :answer, presence: true, length: {:minimum => 50}

end

app/models/question.rb
class Question < ActiveRecord::Base

belongs_to :user
has_many :answers, dependent: :destroy

validates_presence_of :user

validates :title, presence: true, length: {:minimum => 40}
validates :description, presence: true, length: {:minimum => 150}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :questions
has_many :answers


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :authenticate_user!, only: [:destroy, :delete, :new, :create, :edit, :update]

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.user_id = current_user.id
    @answer.question_id = @question.id
    if @answer.save
      redirect_to @question, notice: "Answer was successfully created"
    else
      render :new
    end
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def edit
  end

  def destroy
  end

  def answer_params
    params.require(:answer).permit(:answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  # def after_sign_out_path_for(resource_or_scope)
  #   questions_path
  # end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user!, only: [:destroy, :delete, :new, :create, :edit, :update]


  def index
    @questions = Question.all.order(created_at: :desc)
    @answers = Answer.all
  end

  def show
    id = params[:id]
    @question = Question.find(id)
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    if @question.save
      redirect_to @question, :notice => "Question was successfully created"
    else
      render :new
    end
  end

  def edit
    id = params[:id]
    @question = Question.find(id)
    if current_user.id != @question.user_id
      redirect_to @question, notice: "Quit trying to edit Marlon's questions, you jerk cats."
    end
  end

  def update
    id = params[:id]
    @question = Question.find(id)
    @question.update(question_params)

      if @question.save
        redirect_to @question, notice: "Question updated"
      else
        render :edit, notice: "Question did not update"
      end
  end

    def new
      @question = Question.new
    end

    def destroy
      id = params[:id]
      @question = Question.find(id)
      @question.destroy
      redirect_to questions_path
    end

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/helpers/answers_controller_helper.rb
module AnswersControllerHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/new.html.erb
<h1>Post your answer</h1>

<div>
<h2><%= @question.title %></h2>
<h3><%= @question.description %></h3>
<h5><%= @question.user.email %></h5>
</div>

<%= form_for([@question, @answer]) do |f| %>
<% if @answer.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this question from being saved:</h2>
  <ul>
    <% @answer.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :answer %><br>
  <%= f.text_area :answer %>
</div>

<div class="actions">
  <button><% f.submit %>Submit answer</button>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Space Overflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <a href="/questions"><h1 class="header">SpaceOverflow</h1></a>


<% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
  <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
<% if @question.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
  <ul>
    <% @question.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit your question</h1>
<%= render 'form' %>

app/views/questions/index.html.erb
<div class="questions">
<a href="/questions/new">Ask a new question</a>
</div>

<div>
<% @questions.each do |question| %>
<a href="/questions/<%=question.id%>"><h2>Question title: <%= question.title %> from <%= question.user.email %></h2></a>
  <h4>Question: <%= question.description %></h4>
  <div class="button">
  <a href="/questions/<%=question.id%>/answers/new">Submit an answer</a>
  </div>
</div>

<div>
  <% question.answers.each do |answer| %>
    <h4>Answer: <%= answer.answer %> from <%= answer.user.email %></h4>
    <% end %>
    <% end %>
</div>

app/views/questions/new.html.erb
<h1>Post a new question</h1>
<%= render 'form' %>

app/views/questions/show.html.erb
<div>
<h1><%= @question.title %></h1>
<h2><%= @question.description %></h2>
<h5><%= @question.user.email %></h5>
</div>

<% if current_user %>
  <% if current_user.id == @question.user_id %>
    <div class="button">
        <%= link_to "Delete", @question, method: :delete, data: { confirm: "Are you sure?"}%>
    </div>
  <% end %>
<% end %>

<div class="button">
<a href="/questions/<%= @question.id %>/answers/new">Submit an answer</a>
</div>

<% if current_user %>
  <% if current_user.id == @question.user_id %>
    <div class="button">
      <%= link_to "Edit", edit_question_path(@question) %>
    </div>
  <% end %>
<% end %>

<div>
<% @question.answers.each do |answer| %>
<h2><%= answer.answer %></h2>
<h5><%= answer.user.email %></h5>
<% end %>
</div>